import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button, Container, Typography, Box, Grid, Paper } from "@mui/material";
import Promo from "../assets/promo.png";
import CardTour from "@/components/CardTour";
import Artikel from "@/components/Artikel";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Orvala Tour</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ bgcolor: "red", height: "680px" }}>
        <Container maxWidth="xl"></Container>
      </Box>

      <Container maxWidth="lg">
        {" "}
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",

            marginY: "90px",
            height: "300px",
            borderRadius: "5px",
            backgroundImage: `url(${Promo.src})`,
            backgroundPosition: "center",
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            flexGrow: 1,
            textAlign: "center", // Pusatkan teks horizontal
          }}
        >
          <Typography
            color={"black"}
            textAlign="center"
            fontSize={"32px"}
            fontWeight={"500"}
          >
            EXPLORE UZBEKISTAN
          </Typography>{" "}
          <Typography
            color={"black"}
            textAlign="center"
            fontSize={"15px"}
            fontWeight={"500"}
          >
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat.
          </Typography>
          <Button
            variant="contained"
            sx={{
              borderRadius: "50px",
              paddingY: "17px",
              paddingX: "24px",
              fontSize: "18px",
              marginTop: "10px",
            }}
          >
            View Trip
          </Button>
        </Box>
        <Typography
          color={"black"}
          textAlign="center"
          fontSize={"32px"}
          fontWeight={"500"}
        >
          PROMO TRIP
        </Typography>
        <Grid container flexGrow={1} justifyContent="space-between" mt={"30px"}>
          <CardTour />
          <CardTour />
          <CardTour />
        </Grid>
        <Grid
          container
          justifyContent="center"
          alignItems="center"
          marginTop={"40px"}
          marginBottom={"50px"}
        >
          <Button
            variant="contained"
            color="primary" // Ganti warna sesuai kebutuhan Anda
            sx={{
              borderRadius: "50px",
              paddingY: "17px",
              paddingX: "24px",
              fontSize: "18px",
            }}
          >
            SEE ALL DEALS
          </Button>
        </Grid>
      </Container>
      <Container maxWidth="lg">
        <Typography
          color={"black"}
          textAlign="center"
          fontSize={"32px"}
          fontWeight={"500"}
        >
          WHAT YOU NEED TO KNOW
        </Typography>
        <Grid
          container
          justifyContent="center"
          alignItems="center"
          marginTop={"40px"}
          marginBottom={"50px"}
        >
          <Artikel />
          <Artikel />
          <Artikel />
        </Grid>
        <Typography
          color={"black"}
          textAlign="center"
          fontSize={"32px"}
          fontWeight={"500"}
        >
          WHERE WE GO
        </Typography>
        <Grid
          container
          justifyContent="center"
          alignItems="center"
          marginTop={"40px"}
          marginBottom={"50px"}
        >
          <Grid item xs={12} md={3} sm={6} p={"5px"} mb={"30px"}>
            <Paper>
              <Box
                sx={{
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "end",
                  height: "230px",

                  borderRadius: "5px 5px 0px 0px",
                  backgroundImage: `url(${Promo.src})`,
                  backgroundPosition: "center",
                  backgroundSize: "cover",
                  backgroundRepeat: "no-repeat",
                }}
              >
                <Box
                  sx={{
                    backgroundImage:
                      "linear-gradient(to bottom, rgba(255,0,0,0), black)",
                    color: "white",
                    width: "100%",
                    height: "45px",
                  }}
                >
                  <Typography textAlign={"center"} fontSize={"24px"}>
                    Rusia
                  </Typography>
                </Box>
              </Box>
            </Paper>
          </Grid>
          <Grid item xs={12} md={3} sm={6} p={"5px"} mb={"30px"}>
            <Paper>
              <Box
                sx={{
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "center",
                  height: "230px",

                  borderRadius: "5px 5px 0px 0px",
                  backgroundImage: `url(${Promo.src})`,
                  backgroundPosition: "center",
                  backgroundSize: "cover",
                  backgroundRepeat: "no-repeat",
                }}
              ></Box>
            </Paper>
          </Grid>{" "}
          <Grid item xs={12} md={3} sm={6} p={"5px"} mb={"30px"}>
            <Paper>
              <Box
                sx={{
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "center",
                  height: "230px",

                  borderRadius: "5px 5px 0px 0px",
                  backgroundImage: `url(${Promo.src})`,
                  backgroundPosition: "center",
                  backgroundSize: "cover",
                  backgroundRepeat: "no-repeat",
                }}
              ></Box>
            </Paper>
          </Grid>{" "}
          <Grid item xs={12} md={3} sm={6} p={"5px"} mb={"30px"}>
            <Paper>
              <Box
                sx={{
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "center",
                  height: "230px",

                  borderRadius: "5px 5px 0px 0px",
                  backgroundImage: `url(${Promo.src})`,
                  backgroundPosition: "center",
                  backgroundSize: "cover",
                  backgroundRepeat: "no-repeat",
                }}
              ></Box>
            </Paper>
          </Grid>
        </Grid>
      </Container>
    </>
  );
}
